package edu.fnosari.momedm.activities.main.screens

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import edu.fnosari.momedm.R
import edu.fnosari.momedm.activities.main.ControllerViewModel
import edu.fnosari.momedm.controller.provisioning.QrBitmap
import edu.fnosari.momedm.persistence.ControllerPrefs

@Composable
fun ProvisionScreen(navController: NavHostController, viewModel: ControllerViewModel) {
    val pc = viewModel.provisioning
    val s by pc.state.collectAsState()
    DisposableEffect(Unit) { onDispose { pc.stop() } }
    Column(Modifier.fillMaxWidth().padding(16.dp).verticalScroll(rememberScrollState()), verticalArrangement = Arrangement.spacedBy(12.dp), horizontalAlignment = Alignment.CenterHorizontally) {
        Text(stringResource(R.string.provision_mode), style = MaterialTheme.typography.titleMedium, modifier = Modifier.fillMaxWidth())
        listOf(ControllerPrefs.MODE_HOTSPOT to R.string.provision_mode_hotspot, ControllerPrefs.MODE_MANUAL to R.string.provision_mode_manual, ControllerPrefs.MODE_CUSTOM_URL to R.string.provision_mode_custom).forEach { (mode, label) ->
            Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) { RadioButton(selected = s.mode == mode, onClick = { pc.setMode(mode) }); Text(stringResource(label)) }
        }
        if (s.mode == ControllerPrefs.MODE_HOTSPOT) {
            // Hotspot credentials are transient and generated by the platform; show them read-only once available.
            if (s.hotspotSsid.isNotBlank()) {
                Text("${stringResource(R.string.provision_ssid)}: ${s.hotspotSsid}", style = MaterialTheme.typography.bodyMedium, modifier = Modifier.fillMaxWidth())
                Text("${stringResource(R.string.provision_password)}: ${s.hotspotPassword}", style = MaterialTheme.typography.bodyMedium, modifier = Modifier.fillMaxWidth())
            }
        } else {
            OutlinedTextField(s.ssid, { pc.setManual(it, s.password) }, label = { Text(stringResource(R.string.provision_ssid)) }, singleLine = true, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(s.password, { pc.setManual(s.ssid, it) }, label = { Text(stringResource(R.string.provision_password)) }, singleLine = true, modifier = Modifier.fillMaxWidth())
        }
        if (s.mode == ControllerPrefs.MODE_CUSTOM_URL) OutlinedTextField(s.customUrl, { pc.setCustomUrl(it) }, label = { Text(stringResource(R.string.provision_url)) }, singleLine = true, modifier = Modifier.fillMaxWidth())
        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            Button(onClick = { pc.start() }) { Text(stringResource(R.string.provision_start)) }
            OutlinedButton(onClick = { pc.stop() }) { Text(stringResource(R.string.provision_stop)) }
        }
        s.ip?.takeIf { s.serverRunning }?.let { Text(stringResource(R.string.provision_serving, it), style = MaterialTheme.typography.bodySmall) }
        s.error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
        s.qrPayload?.let { payload ->
            // zxing throws (WriterException) when the payload exceeds what a QR code can hold — e.g. a
            // long custom URL plus credentials. Surface it instead of crashing the whole screen.
            val bmp = remember(payload) { runCatching { QrBitmap.render(payload, 800) }.getOrNull() }
            if (bmp == null) {
                Text(stringResource(R.string.provision_qr_error), color = MaterialTheme.colorScheme.error)
            } else {
                Image(bmp.asImageBitmap(), contentDescription = null, modifier = Modifier.size(320.dp))
                Text(stringResource(R.string.provision_help), style = MaterialTheme.typography.bodySmall)
            }
        }
    }
}
